### PR TITLE
Issue 1 user can create an entry

### PR DESCRIPTION
**Pull request by jnsangalang**
code journal entry-desktop

code journal entry-mobile

### CODE REVIEW

**Comment by jnsangalang** [comment]
code journal entry-desktop2
code journal entry-mobile2

**Comment by jnsangalang** [comment]
image

code journal mobile layout

**Comment by jnsangalang** [comment]
image

**Comment by jnsangalang** [comment]
code journal mobile layout

**Review by shawnkost — APPROVED** [review]
👍🏻

**Pull request merged**
